server:
  port: 8080
spring:
  application:
    name: cj-gateway
  cloud:
    nacos:
      server-addr: 172.30.183.229:8848 # nacos地址
      discovery:
        namespace: choujiang
    gateway:
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**




cj:
  jwt:
    location: classpath:choujiang.jks
    alias: choujiang123
    password: choujiang123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /user/login
      - /items/**
      - /hi