server:
  port: 8081
spring:
  application:
    name: luckDraw-service
  profiles:
    active: dev
  datasource:
    #    url: jdbc:mysql://${cj.db.host}:3306/choujiang?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://172.30.183.229:3306/choujiang?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: taswy1996GY.
  #    password: ${cj.db.pw}
  cloud:
    nacos:
      server-addr: 172.30.183.229:8848 # nacos地址
      discovery:
        namespace: choujiang
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config: # 这里相当于在给所有字段默认注解
      update-strategy: not_null # 字段在非空时才更新
      id-type: auto
logging:
  level:
    com.taswy.choujiang: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
knife4j:
  enable: true
  openapi:
    title: 抽奖平台抽奖服务接口文档
    description: "抽奖平台抽奖服务接口文档"
    email: taswy2020@163.com
    concat: taswy
    url: https://choujiang.taswy.com
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.taswy.choujiang.luckDraw.controller